name: "Setup DOX CLI"
description: "Install and configure DOX CLI for GitHub Actions workflows"
author: "DopxLab"

branding:
  icon: "terminal"
  color: "gray-dark"

inputs:
  custom-dir:
    description: "Custom directory for DOX customization files"
    required: false
    default: "$HOME/.dox/customize"
  resources-dir:
    description: "Directory for DOX resources cache"
    required: false
    default: "$HOME/dox_resources"

runs:
  using: "composite"
  steps:
    - name: Configure DOX environment
      shell: bash
      run: |
        echo "DOX_CUSTOM_DIR=${{ inputs.custom-dir }}" >> $GITHUB_ENV
        echo "DOX_RESOURCES_DIR=${{ inputs.resources-dir }}" >> $GITHUB_ENV
    
    - name: Install DOX CLI
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/dopxlab/dox-cli/main/install.sh | bash
        echo "BASH_ENV=$HOME/.dox/bin/dox-wrapper" >> $GITHUB_ENV